version: '2'
services:
  db:
    image: postgres:9.6
    ports:
      - "5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/happyshop
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
